name: GreenItScan CI Pipeline

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'

      - name: Install Make
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Clean up Docker containers
        run: docker-compose -f docker-compose.yml down -v --remove-orphans

      - name: Build Docker images
        run: make build || { docker-compose -f docker-compose.yml logs; exit 1; }

      - name: Start Docker services
        run: docker-compose -f docker-compose.yml up -d --wait
        timeout-minutes: 10

      - name: Debug Docker services
        run: |
          docker ps -a
          docker-compose -f docker-compose.yml logs frontend
          curl http://localhost:9000 || echo "Frontend not available"

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: |
            quasar-project/cypress/e2e/first.cy.js
            quasar-project/cypress/e2e/login_spec.cy.js
            quasar-project/cypress/e2e/questionnaire_page_spec.cy.js
            quasar-project/cypress/e2e/register_user_spec.cy.js
            quasar-project/cypress/e2e/resultats_page_spec.cy.js
          working-directory: ./quasar-project
          record: false
        env:
          CYPRESS_FRONTEND_URL: http://localhost:9000
          CYPRESS_API_URL: http://localhost:8000

      - name: Upload Cypress E2E artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-e2e-artifacts
          path: |
            quasar-project/cypress/screenshots
            quasar-project/cypress/videos
          retention-days: 7

      - name: Debug Docker logs on failure
        if: failure()
        run: docker-compose -f docker-compose.yml logs

      - name: Stop Docker services
        if: always()
        run: docker-compose -f docker-compose.yml down -v

# cypress-component:
#   runs-on: ubuntu-latest
#   steps:
#     - name: Checkout code
#       uses: actions/checkout@v4
#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '18.19.1'
#         cache: 'npm'
#         cache-dependency-path: quasar-project/package-lock.json
#     - name: Install quasar-project dependencies
#       run: npm ci
#       working-directory: ./quasar-project
#     - name: Run Cypress component tests
#       uses: cypress-io/github-action@v6
#       with:
#         browser: chrome
#         component: true
#         spec: quasar-project/cypress/e2e/card_result_spec.cy.js
#         working-directory: ./quasar-project
#     - name: Upload Cypress component artifacts
#       if: always()
#       uses: actions/upload-artifact@v4
#       with:
#         name: cypress-component-artifacts
#         path: quasar-project/cypress/downloads
#         retention-days: 77