name: GreenItScan CI Pipeline (Final Fix)
on:
  push:
    branches: [cicd]
  pull_request:
    branches: [cicd]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.6'
          extensions: intl, mbstring, xml, zip, bcmath, gd

      - name: Install backend dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-scripts
        working-directory: ./api-backend

      - name: Start backend server
        run: |
          cd api-backend
          nohup php -S 0.0.0.0:8000 -t public public/index.php > php.log 2>&1 &
          sleep 5  # Temps pour démarrer

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
          cache: 'npm'
          cache-dependency-path: quasar-project/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./quasar-project

      - name: Build frontend
        run: npm run build
        working-directory: ./quasar-project

      - name: Install `serve` and start frontend server
        run: |
          cd quasar-project
          npm install -g serve
          nohup serve -s dist/spa -l 9000 > serve.log 2>&1 &
          sleep 5  # Temps pour démarrer

      - name: Verify frontend is ready
        run: |
          MAX_ATTEMPTS=10
          ATTEMPT=0
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9000)
            if [ "$RESPONSE" -eq 200 ]; then
              echo "Frontend is ready!"
              exit 0
            fi
            ATTEMPT=$((ATTEMPT + 1))
            sleep 2
          done
          echo "Frontend did not start correctly."
          cat quasar-project/serve.log
          exit 1

      - name: Verify backend is ready
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/api/doc | grep -q "200" || exit 1

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: quasar-project/cypress/e2e/first.cy.js
          working-directory: ./quasar-project
        env:
          CYPRESS_FRONTEND_URL: http://localhost:9000
          CYPRESS_API_URL: http://localhost:8000

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: quasar-project/cypress/screenshots
          retention-days: 7

      - name: Debug logs on failure
        if: failure()
        run: |
          echo "=== PHP Logs ==="
          cat api-backend/php.log
          echo "=== Serve Logs ==="
          cat quasar-project/serve.log
