name: GreenItScan CI Pipeline (No Database)
on:
  push:
    branches: [cicd]
  pull_request:
    branches: [cicd]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
          cache: 'npm'
          cache-dependency-path: quasar-project/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./quasar-project

      - name: Start frontend server
        run: npm run dev &
        working-directory: ./quasar-project

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.6'
          extensions: intl, mbstring, xml, zip, bcmath, gd

      - name: Install backend dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-scripts --verbose
        working-directory: ./api-backend

      - name: Start backend server (without database)
        run: |
          cd api-backend
          # Désactiver la connexion à la base de données dans l'environnement de test
          export APP_ENV=test
          php -S 0.0.0.0:8000 -t public public/index.php &
        env:
          # Variables pour simuler ou désactiver la base de données
          DATABASE_URL: "none"

      - name: Wait for services
        run: |
          npx wait-on http://localhost:9000 --timeout 30000
          npx wait-on http://localhost:8000/api/doc --timeout 30000

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: |
            quasar-project/cypress/e2e/first.cy.js
            quasar-project/cypress/e2e/login_spec.cy.js
          working-directory: ./quasar-project
        env:
          CYPRESS_FRONTEND_URL: http://localhost:9000
          CYPRESS_API_URL: http://localhost:8000

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            quasar-project/cypress/screenshots
            quasar-project/cypress/videos
          retention-days: 7
