name: GreenItScan CI Pipeline (Fixed for Real)
on:
  push:
    branches: [cicd]
  pull_request:
    branches: [cicd]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.6'
          extensions: intl, mbstring, xml, zip, bcmath, gd

      - name: Install backend dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader --no-scripts --verbose
        working-directory: ./api-backend

      - name: Start backend server
        run: |
          cd api-backend
          php -S 0.0.0.0:8000 -t public public/index.php > php-server.log 2>&1 &
        env:
          APP_ENV: test

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.1'
          cache: 'npm'
          cache-dependency-path: quasar-project/package-lock.json

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./quasar-project

      - name: Build frontend
        run: npm run build
        working-directory: ./quasar-project

      - name: Start frontend server
        run: |
          cd quasar-project
          npx quasar dev > quasar.log 2>&1 &
          sleep 5  # Temps minimal pour le démarrage

      - name: Verify frontend is ready
        run: |
          # Vérifier que la réponse contient bien le titre de l'app Quasar
          MAX_ATTEMPTS=10
          ATTEMPT=0
          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
            RESPONSE=$(curl -s http://localhost:9000)
            if [[ "$RESPONSE" == *"<title>Quasar App</title>"* ]]; then
              echo "Frontend is ready!"
              exit 0
            fi
            ATTEMPT=$((ATTEMPT + 1))
            sleep 2
          done
          echo "Frontend did not start correctly."
          cat quasar-project/quasar.log
          exit 1

      - name: Verify backend is ready
        run: |
          curl -v http://localhost:8000/api/doc || echo "Backend not ready"

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: |
            quasar-project/cypress/e2e/first.cy.js
            quasar-project/cypress/e2e/login_spec.cy.js
          working-directory: ./quasar-project
        env:
          CYPRESS_FRONTEND_URL: http://localhost:9000
          CYPRESS_API_URL: http://localhost:8000

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            quasar-project/cypress/screenshots
            quasar-project/cypress/videos
          retention-days: 7

      - name: Debug logs on failure
        if: failure()
        run: |
          echo "=== PHP Server Logs ==="
          cat api-backend/php-server.log
          echo "=== Quasar Logs ==="
          cat quasar-project/quasar.log
